. ~/.dotfiles/shared/aliases
. ~/.dotfiles/shared/config
. ~/.dotfiles/shared/env

PATH=$PATH:$HOME:/Development/rpi/arm-cs-tools/bin #:$HOME/.rvm/bin # Add RVM to PATH for scripting

# ASDF
source "$HOME/.asdf/asdf.sh"
fpath=(${ASDF_DIR}/completions $fpath)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/lkuhnt/Downloads/google-cloud-sdk/path.bash.inc' ]; then source '/Users/lkuhnt/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/lkuhnt/Downloads/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/lkuhnt/Downloads/google-cloud-sdk/completion.bash.inc'; fi

source /Users/lkuhnt/.docker/init-bash.sh || true # Added by Docker Desktop
export PATH="/usr/local/opt/openjdk/bin:$PATH"

