. ~/.dotfiles/bash/aliases
. ~/.dotfiles/bash/config
. ~/.dotfiles/bash/env

alias mate='say "Lars, du Dummkopf"'

PATH=$PATH:$HOME:/Development/rpi/arm-cs-tools/bin:$HOME/.rvm/bin # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export NVM_DIR="/Users/lkuhnt/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
