. ~/.dotfiles/shared/aliases
. ~/.dotfiles/shared/env

# Prerequisites:
# brew install fzf

# Homebrew
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

alias reload="source ~/.dotfiles/zshrc"

# Mongodb
# export PATH="/usr/local/opt/mongodb-community@3.4/bin:$PATH"

# Postgres
# export PGDATA=$HOME/Postgres@11
export PATH="/usr/local/opt/postgresql@11/bin:$PATH"

# History
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY_TIME
setopt EXTENDED_HISTORY

# Prompt
autoload -Uz vcs_info
zstyle ':vcs_info:git*' formats " %F{yellow}[%b]%F{reset}"
precmd() {
    vcs_info
}
setopt prompt_subst
PROMPT='%F{green}%2/%F{green}${vcs_info_msg_0_} %F{green}> %F{reset}'

# ASDF
source "$HOME/.asdf/asdf.sh"
fpath=(${ASDF_DIR}/completions $fpath)

# Autocompletion
autoload -Uz compinit && compinit
source "$HOME/.fzf/fzf-tab/fzf-tab.plugin.zsh"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

zstyle ':fzf-tab:*' switch-group ',' '.'
zstyle ':fzf-tab:*' fzf-bindings 'space:accept'

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:descriptions' format '[%d]'